sudo: false
language: php
php:
  - 5.6

services:
  - mysql

before_install:
  - openssl aes-256-cbc -K $encrypted_eb8cd28bff04_key -iv $encrypted_eb8cd28bff04_iv -in deploy.secret.key.enc -out ~/.ssh/deploy.secret.key -d

before_script:
  - mysql -e 'create database miserend character set utf8 collate utf8_unicode_ci;'
  - npm install
  - npm install -g bower
  - php composer.phar selfupdate
  - php composer.phar install
  - php install.php

script:
  - phpunit tests
  #- phpunit --configuration phpunit.xml

after_success:
  # Add the ssh key
  - eval "$(ssh-agent)"
  - chmod 600 ~/.ssh/deploy.secret.key
  - ssh-add ~/.ssh/deploy.secret.key
  - echo -e "Host szentiras.hu\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - ssh miserend_hu_git@szentiras.hu "git -C /home/miserend_hu_git/github/borazslo/${TRAVIS_BRANCH}.miserend.hu pull origin ${TRAVIS_BRANCH}"
  - ssh miserend_hu_git@szentiras.hu "php /home/miserend_hu_git/github/borazslo/${TRAVIS_BRANCH}.miserend.hu/migration.php"

env:
  global:
  - ENV=production
  - DB_USERNAME=root
  - DB_PASSWORD=""