sudo: false
language: php
php:
  - 5.6

services:
  - mysql

before_script:
  - mysql -e 'create database miserend character set utf8 collate utf8_unicode_ci;'
  - npm install
  - npm install -g bower
  - php composer.phar selfupdate
  - php composer.phar install
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('root') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
  - php install.php

script:
  - phpunit --version
  - phpunit tests -v
  #- phpunit --configuration phpunit.xml

after_success:
  # Add the ssh key
  - openssl aes-256-cbc -K $encrypted_eb8cd28bff04_key -iv $encrypted_eb8cd28bff04_iv -in deploy.secret.key.enc -out ~/.ssh/deploy.secret.key -d
  - eval "$(ssh-agent)"
  - chmod 600 ~/.ssh/deploy.secret.key
  - ssh-add ~/.ssh/deploy.secret.key
  - echo -e "Host szentiras.hu\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - ssh miserend_hu_git@szentiras.hu "bash -s ${TRAVIS_BRANCH}" < update.sh

env:
  global:
  - MISEREND_WEBAPP_ENVIRONMENT=production
  - MYSQL_MISEREND_USER=root
  - MYSQL_MISEREND_PASSWORD=root