controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

main:
    path: /
    controller:    Symfony\Bundle\FrameworkBundle\Controller\TemplateController

terms_and_conditions:
    path:          /hazirend
    controller:    Symfony\Bundle\FrameworkBundle\Controller\TemplateController
